---
title: "coba PA"
output:
  pdf_document: default
  html_document: default
date: "2024-05-06"
---


```{r}
data<-read.csv("C:/Users/ACER/Documents/KULIAH DEA/SEM 2/PRAKTIKUM PEMODELAN STATISTIKA TERAPAN/dataset proyek akhir.csv",header=TRUE)
data
```

```{r}
tsdata <- ts(data)
ts.plot(tsdata)
summary(tsdata)
```

```{r}
air <- tsdata[,2]
air
plot(air)
```

```{r}
library(tseries)
adf.test(air)
adf.test(diff(air))
plot(diff(air), main = "Air D=1")
```

```{r}
par(mfrow=c(1,1))
acf(diff(air))
pacf(diff(air))
```

```{r}
library(forecast)
arima.1 <- arima(air, order=c(2,1,0))
arima.2 <- arima(air, order=c(0,1,2))
arima.3 <- arima(air, order=c(2,1,2))
summary(arima.1)
summary(arima.2)
summary(arima.3)
```

```{r}
library(lmtest)
coeftest(arima.1)
coeftest(arima.2)
coeftest(arima.3)#koefisien tidak signifikan
```

```{r}
tsdiag(arima.1)
tsdiag(arima.2)
```

```{r}
resid1=arima.1$residuals
resid2=arima.2$residuals
```

```{r}
t.test(resid1, mu=0, alternative = "two.sided")
t.test(resid2, mu=0, alternative = "two.sided")
```

```{r}
pred.data = predict(arima.2, n.ahead=5)
pred.data
pred.data.low = pred.data$pred - 1.96 * pred.data$se
pred.data.up = pred.data$pred + 1.96 * pred.data$se
```

```{r}
dataAIR <- data$Air.Disalurkan
fit.data=fitted(arima.2)
par(mfrow=c(1,1))
ts.plot(dataAIR)
lines(fit.data, col="red")
```
